version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: nfforms-mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: nfforms
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    container_name: nfforms-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    environment:
      - MONGO_URI=mongodb://mongo:27017/nfforms
    depends_on:
      - mongo
    restart: unless-stopped
    
  frontend:
    build:
      context: ./frontend-app
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL:-http://localhost:5000/api}
        REACT_APP_GOOGLE_CLIENT_ID: ${REACT_APP_GOOGLE_CLIENT_ID:-486170631932-lk7chbd259154reeqpe0a89ksb3rbr6i.apps.googleusercontent.com}
    container_name: nfforms-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo-data:
